<?php
/** @var Magento\Framework\View\Element\Template $block */?>
<!-- Script -->
<script type="text/x-magento-init">
    {
        "*" :{
           "objectEditor": {},
           "Magento_Ui/js/core/app": {
                "components": {
                    "ui-creator": {
                        "component": "Magento_Theme/js/ui-creator"
                    }
                }
           }
        }
    }
 </script>


